### ISSUE TITLE
[Bug]: Android9.0 x86_x64车机系统播放音乐卡死闪退

### ISSUE THREAD

**Issue by lxmou666** [lyswhut/lx-music-mobile#129]
### 解决方案检查

- [X] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-mobile/blob/master/FAQ.md>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

**app能正常进入，并且能看到歌单搜索歌曲等。但是点击播放就会卡死并最终导致app崩溃退出。**

### 实际行为

`2022-06-11 14:24:51.601 10490-10490 AndroidRuntime          pid-10490                            E  FATAL EXCEPTION: main
                                                                                                    Process: cn.toside.music.mobile, PID: 10490
                                                                                                    java.lang.RuntimeException: Unable to start service com.guichaguri.trackplayer.service.MusicService@54fc54c with Intent { cmp=cn.toside.music.mobile/com.guichaguri.trackplayer.service.MusicService }: java.lang.NullPointerException: Attempt to invoke virtual method 'android.net.wifi.WifiManager$WifiLock android.net.wifi.WifiManager.createWifiLock(int, java.lang.String)' on a null object reference
                                                                                                    	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3686)
                                                                                                    	at android.app.ActivityThread.access$1600(ActivityThread.java:199)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1681)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:193)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6669)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:880)
                                                                                                    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.net.wifi.WifiManager$WifiLock android.net.wifi.WifiManager.createWifiLock(int, java.lang.String)' on a null object reference
                                                                                                    	at com.guichaguri.trackplayer.service.b.<init>(Unknown Source:63)
                                                                                                    	at com.guichaguri.trackplayer.service.MusicService.onStartCommand(Unknown Source:36)
                                                                                                    	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3667)
                                                                                                    	at android.app.ActivityThread.access$1600(ActivityThread.java:199) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1681) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loop(Looper.java:193) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6669) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:880) `

`2022-06-11 14:24:56.658 10490-10519 AndroidRuntime          pid-10490                            E  FATAL EXCEPTION: mqt_native_modules
                                                                                                    Process: cn.toside.music.mobile, PID: 10490
                                                                                                    java.lang.RuntimeException: Could not invoke Networking.abortRequest
                                                                                                    	at com.facebook.react.bridge.JavaMethodWrapper.invoke(Unknown Source:192)
                                                                                                    	at com.facebook.react.bridge.JavaModuleWrapper.invoke(Unknown Source:147)
                                                                                                    	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:873)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(Unknown Source:0)
                                                                                                    	at android.os.Looper.loop(Looper.java:193)
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(Unknown Source:37)
                                                                                                    	at java.lang.Thread.run(Thread.java:764)
                                                                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.facebook.react.bridge.JavaMethodWrapper.invoke(Unknown Source:148)
                                                                                                    	at com.facebook.react.bridge.JavaModuleWrapper.invoke(Unknown Source:147) 
                                                                                                    	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:873) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(Unknown Source:0) 
                                                                                                    	at android.os.Looper.loop(Looper.java:193) 
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(Unknown Source:37) 
                                                                                                    	at java.lang.Thread.run(Thread.java:764) 
                                                                                                    Caused by: java.lang.InternalError: Thread starting during runtime shutdown
                                                                                                    	at java.lang.Thread.nativeCreate(Native Method)
                                                                                                    	at java.lang.Thread.start(Thread.java:733)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:975)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1382)
                                                                                                    	at android.os.AsyncTask$SerialExecutor.scheduleNext(AsyncTask.java:258)
                                                                                                    	at android.os.AsyncTask$SerialExecutor.execute(AsyncTask.java:252)
                                                                                                    	at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:651)
                                                                                                    	at android.os.AsyncTask.execute(AsyncTask.java:595)
                                                                                                    	at com.facebook.react.modules.network.NetworkingModule.cancelRequest(Unknown Source:12)
                                                                                                    	at com.facebook.react.modules.network.NetworkingModule.abortRequest(Unknown Source:1)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.facebook.react.bridge.JavaMethodWrapper.invoke(Unknown Source:148) 
                                                                                                    	at com.facebook.react.bridge.JavaModuleWrapper.invoke(Unknown Source:147) 
                                                                                                    	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:873) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(Unknown Source:0) 
                                                                                                    	at android.os.Looper.loop(Looper.java:193) 
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(Unknown Source:37) 
                                                                                                    	at java.lang.Thread.run(Thread.java:764) `

### Lx Music 版本

0.13.0

### 操作系统版本

Android 9.0

**Comment by lyswhut** [comment]
看起来是在调用`createWifiLock`时崩溃了，我现在直接移除了这部分代码（不知道会不会对手机的后台播放音乐有影响，观察一段时间再说），你可以去试试测试版看现在还会不会崩溃：
https://github.com/lyswhut/lx-music-mobile/actions/workflows/beta-pack.yml

**Comment by lxmou666** [comment]
@lyswhut 
安装了测试版手机后台正常，车机还是崩溃
`lx-music-mobile-v0.14.0-beta.4-x86_64.apk`

**Comment by lyswhut** [comment]
有没有崩溃日志

**Comment by lxmou666** [comment]
@lyswhut 
日志文件已经发送到邮箱

**Comment by lyswhut** [comment]
还是同一个问题，我把包反编译了一下，代码还是旧的，我又把代码撤回去了，加了空判断，现在代码是最新的了，你再试试beta.5

**Comment by lxmou666** [comment]
> 还是同一个问题，我把包反编译了一下，代码还是旧的，我又把代码撤回去了，加了空判断，现在代码是最新的了，你再试试beta.5

已经正常播放了

**Comment by lyswhut** [comment]
已在v0.14.0修复
