### ISSUE TITLE
[Bug]: 清除缓存再查看日志，软件会崩溃

### ISSUE THREAD

**Issue by SunshineboyZj** [lyswhut/lx-music-mobile#340]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/mobile/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-mobile/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

清除缓存再查看日志，软件不会崩溃

### 实际行为

清除缓存再查看日志，软件会崩溃

https://github.com/lyswhut/lx-music-mobile/assets/81549837/f4a2efb7-db24-4241-877c-50723e199692

### Lx Music 版本

1.1.1 arm64-v8a

### 操作系统版本

Android 13

### 附加信息

2023/10/22 13:50:18 ERROR java.lang.RuntimeException: java.io.FileNotFoundException: /data/user/0/cn.toside.music.mobile/cache/error.log: open failed: ENOENT (No such file or directory)
	at cn.toside.music.mobile.utils.c.e(Unknown Source:18)
	at cn.toside.music.mobile.utils.c.b(Unknown Source:0)
	at cn.toside.music.mobile.utils.a.run(Unknown Source:6)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1015)
Caused by: java.io.FileNotFoundException: /data/user/0/cn.toside.music.mobile/cache/error.log: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:574)
	at java.io.FileInputStream.<init>(FileInputStream.java:160)
	at cn.toside.music.mobile.utils.d.d(Unknown Source:7)
	at cn.toside.music.mobile.utils.d$a.a(Unknown Source:2)
	at cn.toside.music.mobile.utils.d$a.call(Unknown Source:0)
	at cn.toside.music.mobile.utils.c.e(Unknown Source:0)
	... 5 more
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8390)
	at libcore.io.IoBridge.open(IoBridge.java:560)
	... 10 more

**Comment by lyswhut** [comment]
已在 1.2.0-beta.5 修复
