### ISSUE TITLE
源码本地编译报错，折腾几天了还是没有解决，寻求帮助

### ISSUE THREAD

**Issue by nitianziluli** [lyswhut/lx-music-mobile#646]
clone 源码后，只修改了仓库地址为国内源，然后按照文档运行，报这个错误：

```
> Task :react-native-quick-base64:configureCMakeDebug[x86_64] FAILED
Execution failed for task ':react-native-quick-base64:configureCMakeDebug[x86_64]'.
> [CXX1429] error when building with cmake using E:\Android\workspace\lx-music-mobile\node_modules\
react-native-quick-base64\android\CMakeLists.txt: C++ build system [prefab] failed while executing:
```

查了好多资料也没找到遇到同样问题的，只有一些较为相似的问题，按照这些回答，尝试了很多办法，依然无法解决，不知道有没有大佬知道怎么解决这个问题。

**Comment by lyswhut** [comment]
错误日志不完整，试试dev分支的代码

**Comment by lyswhut** [comment]
这个错误没有印象遇到过，试试dev分支的代码，CI 跟我本地是可以构建成功的

**Comment by qwe28256** [comment]
代理和版本node问题

**Comment by shixin-code** [comment]
请问编译时有遇到这个问题吗？nodejs: v18.20.8, jdk: 17.0.12 2024-07-16 LTS
```
1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':react-native-pager-view:compileDebugJavaWithJavac'.
> Could not resolve all files for configuration ':react-native-pager-view:androidJdkImage'.
   > Failed to transform core-for-system-modules.jar to match attributes {artifactType=_internal_android_jdk_image, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for JdkImageTransform: D:\dev\Android\Sdk\platforms\android-35\core-for-system-modules.jar.
         > Error while executing process C:\Users\shixi\.jdks\graalvm-jdk-17.0.12\bin\jlink.exe with arguments {--module-path C:\Users\shixi\.gradle\caches\8.8\transforms\7c30c83013867725c317c397b2d696a5-d58382f4-2459-4455-93e5-7d6c34922572\transformed\output\temp\jmod --add-modules java.base --output C:\Users\shixi\.gradle\caches\8.8\transforms\7c30c83013867725c317c397b2d696a5-d58382f4-2459-4455-93e5-7d6c34922572\transformed\output\jdkImage --disable-plugin system-modules}

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':react-native-pager-view:compileDebugJavaWithJavac'.
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:38)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:209)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:166)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:42)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:331)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:318)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.lambda$execute$0(DefaultTaskExecutionGraph.java:314)
	at org.gradle.internal.operations.CurrentBuildOperationRef.with(CurrentBuildOperationRef.java:80)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:314)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:303)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:463)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:380)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:47)
Caused by: org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration 

```

```
2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':react-native-navigation:compileReactNative71DebugJavaWithJavac'.
> Could not resolve all files for configuration ':react-native-navigation:androidJdkImage'.
   > Failed to transform core-for-system-modules.jar to match attributes {artifactType=_internal_android_jdk_image, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for JdkImageTransform: D:\dev\Android\Sdk\platforms\android-35\core-for-system-modules.jar.
         > Error while executing process C:\Users\shixi\.jdks\graalvm-jdk-17.0.12\bin\jlink.exe with arguments {--module-path C:\Users\shixi\.gradle\caches\8.8\transforms\7c30c83013867725c317c397b2d696a5-d58382f4-2459-4455-93e5-7d6c34922572\transformed\output\temp\jmod --add-modules java.base --output C:\Users\shixi\.gradle\caches\8.8\transforms\7c30c83013867725c317c397b2d696a5-d58382f4-2459-4455-93e5-7d6c34922572\transformed\output\jdkImage --disable-plugin system-modules}
```

```
3: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':react-native-async-storage_async-storage:compileDebugJavaWithJavac'.
> Could not resolve all files for configuration ':react-native-async-storage_async-storage:androidJdkImage'.
   > Failed to transform core-for-system-modules.jar to match attributes {artifactType=_internal_android_jdk_image, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for JdkImageTransform: D:\dev\Android\Sdk\platforms\android-35\core-for-system-modules.jar.
         > Error while executing process C:\Users\shixi\.jdks\graalvm-jdk-17.0.12\bin\jlink.exe with arguments {--module-path C:\Users\shixi\.gradle\caches\8.8\transforms\7c30c83013867725c317c397b2d696a5-d58382f4-2459-4455-93e5-7d6c34922572\transformed\output\temp\jmod --add-modules java.base --output C:\Users\shixi\.gradle\caches\8.8\transforms\7c30c83013867725c317c397b2d696a5-d58382f4-2459-4455-93e5-7d6c34922572\transformed\output\jdkImage --disable-plugin system-modules}
```

**Comment by qwe28256** [comment]
真的b不住了



在 2025-04-22 21:18:54，"Beny" ***@***.***> 写道：

请问编译时有遇到这个问题吗？nodejs: v18.20.8, jdk: 17.0.12 2024-07-16 LTS

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':react-native-pager-view:compileDebugJavaWithJavac'.
> Could not resolve all files for configuration ':react-native-pager-view:androidJdkImage'.
   > Failed to transform core-for-system-modules.jar to match attributes {artifactType=_internal_android_jdk_image, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for JdkImageTransform: D:\dev\Android\Sdk\platforms\android-35\core-for-system-modules.jar.
         > Error while executing process C:\Users\shixi\.jdks\graalvm-jdk-17.0.12\bin\jlink.exe with arguments {--module-path C:\Users\shixi\.gradle\caches\8.8\transforms\7c30c83013867725c317c397b2d696a5-d58382f4-2459-4455-93e5-7d6c34922572\transformed\output\temp\jmod --add-modules java.base --output C:\Users\shixi\.gradle\caches\8.8\transforms\7c30c83013867725c317c397b2d696a5-d58382f4-2459-4455-93e5-7d6c34922572\transformed\output\jdkImage --disable-plugin system-modules}

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':react-native-pager-view:compileDebugJavaWithJavac'.
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:38)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:209)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:166)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:42)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:331)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:318)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.lambda$execute$0(DefaultTaskExecutionGraph.java:314)
	at org.gradle.internal.operations.CurrentBuildOperationRef.with(CurrentBuildOperationRef.java:80)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:314)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:303)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:463)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:380)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:47)
Caused by: org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration 


2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':react-native-navigation:compileReactNative71DebugJavaWithJavac'.
> Could not resolve all files for configuration ':react-native-navigation:androidJdkImage'.
   > Failed to transform core-for-system-modules.jar to match attributes {artifactType=_internal_android_jdk_image, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for JdkImageTransform: D:\dev\Android\Sdk\platforms\android-35\core-for-system-modules.jar.
         > Error while executing process C:\Users\shixi\.jdks\graalvm-jdk-17.0.12\bin\jlink.exe with arguments {--module-path C:\Users\shixi\.gradle\caches\8.8\transforms\7c30c83013867725c317c397b2d696a5-d58382f4-2459-4455-93e5-7d6c34922572\transformed\output\temp\jmod --add-modules java.base --output C:\Users\shixi\.gradle\caches\8.8\transforms\7c30c83013867725c317c397b2d696a5-d58382f4-2459-4455-93e5-7d6c34922572\transformed\output\jdkImage --disable-plugin system-modules}

3: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':react-native-async-storage_async-storage:compileDebugJavaWithJavac'.
> Could not resolve all files for configuration ':react-native-async-storage_async-storage:androidJdkImage'.
   > Failed to transform core-for-system-modules.jar to match attributes {artifactType=_internal_android_jdk_image, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for JdkImageTransform: D:\dev\Android\Sdk\platforms\android-35\core-for-system-modules.jar.
         > Error while executing process C:\Users\shixi\.jdks\graalvm-jdk-17.0.12\bin\jlink.exe with arguments {--module-path C:\Users\shixi\.gradle\caches\8.8\transforms\7c30c83013867725c317c397b2d696a5-d58382f4-2459-4455-93e5-7d6c34922572\transformed\output\temp\jmod --add-modules java.base --output C:\Users\shixi\.gradle\caches\8.8\transforms\7c30c83013867725c317c397b2d696a5-d58382f4-2459-4455-93e5-7d6c34922572\transformed\output\jdkImage --disable-plugin system-modules}


—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***>

shixin-code left a comment (lyswhut/lx-music-mobile#646)

请问编译时有遇到这个问题吗？nodejs: v18.20.8, jdk: 17.0.12 2024-07-16 LTS

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':react-native-pager-view:compileDebugJavaWithJavac'.
> Could not resolve all files for configuration ':react-native-pager-view:androidJdkImage'.
   > Failed to transform core-for-system-modules.jar to match attributes {artifactType=_internal_android_jdk_image, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for JdkImageTransform: D:\dev\Android\Sdk\platforms\android-35\core-for-system-modules.jar.
         > Error while executing process C:\Users\shixi\.jdks\graalvm-jdk-17.0.12\bin\jlink.exe with arguments {--module-path C:\Users\shixi\.gradle\caches\8.8\transforms\7c30c83013867725c317c397b2d696a5-d58382f4-2459-4455-93e5-7d6c34922572\transformed\output\temp\jmod --add-modules java.base --output C:\Users\shixi\.gradle\caches\8.8\transforms\7c30c83013867725c317c397b2d696a5-d58382f4-2459-4455-93e5-7d6c34922572\transformed\output\jdkImage --disable-plugin system-modules}

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':react-native-pager-view:compileDebugJavaWithJavac'.
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:38)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:209)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:166)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:42)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:331)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:318)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.lambda$execute$0(DefaultTaskExecutionGraph.java:314)
	at org.gradle.internal.operations.CurrentBuildOperationRef.with(CurrentBuildOperationRef.java:80)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:314)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:303)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:463)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:380)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:47)
Caused by: org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration 


2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':react-native-navigation:compileReactNative71DebugJavaWithJavac'.
> Could not resolve all files for configuration ':react-native-navigation:androidJdkImage'.
   > Failed to transform core-for-system-modules.jar to match attributes {artifactType=_internal_android_jdk_image, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for JdkImageTransform: D:\dev\Android\Sdk\platforms\android-35\core-for-system-modules.jar.
         > Error while executing process C:\Users\shixi\.jdks\graalvm-jdk-17.0.12\bin\jlink.exe with arguments {--module-path C:\Users\shixi\.gradle\caches\8.8\transforms\7c30c83013867725c317c397b2d696a5-d58382f4-2459-4455-93e5-7d6c34922572\transformed\output\temp\jmod --add-modules java.base --output C:\Users\shixi\.gradle\caches\8.8\transforms\7c30c83013867725c317c397b2d696a5-d58382f4-2459-4455-93e5-7d6c34922572\transformed\output\jdkImage --disable-plugin system-modules}

3: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':react-native-async-storage_async-storage:compileDebugJavaWithJavac'.
